test:
  solr:
    hostname: localhost
    port: 8980
development:
  solr:
    hostname: localhost
    port: 8981
config_test:
  solr:
    hostname: some.host
    port: 1234
    path: /solr/idx
    log_level: WARNING
    solr_home: /another/path/solr
  auto_commit_after_request: false
