rvm:
  - 1.8.6
  - 1.8.7
  - 1.9.2
  - rbx
  - rbx-2.0
  - ree
  - jruby

notifications:
  recipients:
    - nick@onemorecloud.com

script: "bundle exec rake"

before_script:
  - cd sunspot
  - bundle install